#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=16
#SBATCH --cpus-per-task=1
#SBATCH --time=1:00:00
#SBATCH --job-name mpi
#SBATCH --output=mpi_%j.out


module load StdEnv/2023
module load intel/2023.2.1
module load intelmpi/2021.9.0


rm mpi_sum.txt
srun -n 1 -o 0 ./serial -n 10000 -no -s mpi_sum.txt
srun -n 1 -o 0 ./mpi -n 10000 -no -s mpi_sum.txt
srun -n 2 -o 0 ./mpi -n 10000 -no -s mpi_sum.txt
srun -n 4 -o 0 ./mpi -n 10000 -no -s mpi_sum.txt
srun -n 8 -o 0 ./mpi -n 10000 -no -s mpi_sum.txt
srun -n 16 -o 0 ./mpi -n 10000 -no -s mpi_sum.txt
#srun -n 1 -o 0 ./mpi -n 10000 -no -s mpi_sum.txt
srun -n 2 -o 0 ./mpi -n 20000 -no -s mpi_sum.txt
srun -n 4 -o 0 ./mpi -n 40000 -no -s mpi_sum.txt
srun -n 8 -o 0 ./mpi -n 80000 -no -s mpi_sum.txt
srun -n 16 -o 0 ./mpi -n 160000 -no -s mpi_sum.txt
srun -n 1 -o 0 ./autograder -v mpi -s mpi_sum.txt
